export const browserCoreExamples = [
  "fastclaw browser status",
  "fastclaw browser start",
  "fastclaw browser stop",
  "fastclaw browser tabs",
  "fastclaw browser open https://example.com",
  "fastclaw browser focus abcd1234",
  "fastclaw browser close abcd1234",
  "fastclaw browser screenshot",
  "fastclaw browser screenshot --full-page",
  "fastclaw browser screenshot --ref 12",
  "fastclaw browser snapshot",
  "fastclaw browser snapshot --format aria --limit 200",
  "fastclaw browser snapshot --efficient",
  "fastclaw browser snapshot --labels",
];

export const browserActionExamples = [
  "fastclaw browser navigate https://example.com",
  "fastclaw browser resize 1280 720",
  "fastclaw browser click 12 --double",
  'fastclaw browser type 23 "hello" --submit',
  "fastclaw browser press Enter",
  "fastclaw browser hover 44",
  "fastclaw browser drag 10 11",
  "fastclaw browser select 9 OptionA OptionB",
  "fastclaw browser upload /tmp/fastclaw/uploads/file.pdf",
  'fastclaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "fastclaw browser dialog --accept",
  'fastclaw browser wait --text "Done"',
  "fastclaw browser evaluate --fn '(el) => el.textContent' --ref 7",
  "fastclaw browser console --level error",
  "fastclaw browser pdf",
];
